In [1]:
#map함수 중요하다.

In [3]:
#pandas에서 plot을 만들수있다. transpose를 이용해 x와y 전치가능
import pandas as pd
import matplotlib.pyplot as plt
#plot의 kind파라미터 바꾸면서 시각화형태변경가능
df1 = pd.read_excel('./data/남북한발전전력량.xlsx',engine='openpyxl')
df = df1.iloc[[0,5],3:]
df.index=['S','N']
df.columns.map(int)
df.T.plot()

ImportError: DLL load failed while importing _imaging: 지정된 모듈을 찾을 수 없습니다.

In [3]:
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_excel('./data/시도별 전출입 인구수.xlsx',engine='openpyxl')
df.head(10)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182
5,NaN,인천광역시,-,-,-,-,-,-,-,-,...,565585,478169,462051,499567,468666,461613,452297,473223,441646,409465
6,NaN,광주광역시,-,-,-,-,-,-,-,-,...,268757,293879,268574,260561,228612,226696,243066,224603,213176,208138
7,NaN,대전광역시,-,-,-,-,-,-,-,-,...,263532,252424,262432,264244,239635,230858,239559,220774,219252,211449
8,NaN,울산광역시,-,-,-,-,-,-,-,-,...,181662,159953,161146,164963,161433,159492,176015,170393,148190,135199
9,NaN,세종특별자치시,-,-,-,-,-,-,-,-,...,-,-,-,-,32784,23805,56526,83994,65052,82073

In [16]:
df=df.fillna(method='ffill')#ffill앞의정보로 채운다.
df.head()
print(df['전출지별'])
print(df['전출지별']=='서울특별시')#서울특별시와 비교한 결과

0         전출지별
1           전국
2           전국
3           전국
4           전국
        ...
320    제주특별자치도
321    제주특별자치도
322    제주특별자치도
323    제주특별자치도
324    제주특별자치도
Name: 전출지별, Length: 325, dtype: object
0      False
1      False
2      False
3      False
4      False
       ...
320    False
321    False
322    False
323    False
324    False
Name: 전출지별, Length: 325, dtype: bool

In [22]:
mask = (df['전출지별']=='서울특별시')&(df['전입지별']!='서울특별시')
print(mask)
df_seoul = df[mask]#새로운index생성
print(df_seoul)

0      False
1      False
2      False
3      False
4      False
       ...
320    False
321    False
322    False
323    False
324    False
Length: 325, dtype: bool
     전출지별     전입지별     1970     1971     1972     1973     1974     1975  \
19  서울특별시       전국  1448985  1419016  1210559  1647268  1819660  2937093
21  서울특별시    부산광역시    11568    11130    11768    16307    22220    27515
22  서울특별시    대구광역시        -        -        -        -        -        -
23  서울특별시    인천광역시        -        -        -        -        -        -
24  서울특별시    광주광역시        -        -        -        -        -        -
25  서울특별시    대전광역시        -        -        -        -        -        -
26  서울특별시    울산광역시        -        -        -        -        -        -
27  서울특별시  세종특별자치시        -        -        -        -        -        -
28  서울특별시      경기도   130149   150313    93333   143234   149045   253705
29  서울특별시      강원도     9352    12885    13561    16481    15479    27837
30  서울특별시     충청북도     6700     9457    10853    12617    11786    21073
31  서울특별시     충청남도    15954    18943    23406    27139    25509    51205
32  서울특별시     전라북도    10814    13192    16583    18642    16647    34411
33  서울특별시     전라남도    10513    16755    20157    22160    21314    46610
34  서울특별시     경상북도    11868    16459    22073    27531    26902    46177
35  서울특별시     경상남도     8409    10001    11263    15193    16771    23150
36  서울특별시  제주특별자치도     1039     1325     1617     2456     2261     3440

       1976     1977  ...     2008     2009     2010     2011     2012  \
19  2495620  2678007  ...  2083352  1925452  1848038  1834806  1658928
21    23732    27213  ...    17353    17738    17418    18816    16135
22        -        -  ...     9720    10464    10277    10397    10135
23        -        -  ...    50493    45392    46082    51641    49640
24        -        -  ...    10846    11725    11095    10587    10154
25        -        -  ...    13515    13632    13819    13900    14080
26        -        -  ...     5057     4845     4742     5188     5691
27        -        -  ...        -        -        -        -     2998
28   202276   207722  ...   412408   398282   410735   373771   354135
29    25927    25415  ...    23668    23331    22736    23624    22332
30    18029    17478  ...    15294    15295    15461    15318    14555
31    41447    43993  ...    27458    24889    24522    24723    22269
32    29835    28444  ...    18390    18332    17569    17755    16120
33    46251    43430  ...    16601    17468    16429    15974    14765
34    40376    41155  ...    15425    16569    16042    15818    15191
35    22400    27393  ...    15438    15303    15689    16039    14474
36     3623     3551  ...     5473     5332     5714     6133     6954

       2013     2014     2015     2016     2017
19  1620640  1661425  1726687  1655859  1571423
21    16153    17320    17009    15062    14484
22    10631    10062    10191     9623     8891
23    47424    43212    44915    43745    40485
24     9129     9759     9216     8354     7932
25    13440    13403    13453    12619    11815
26     5542     6047     5950     5102     4260
27     2851     6481     7550     5943     5813
28   340801   332785   359337   370760   342433
29    20601    21173    22659    21590    21016
30    13783    14244    14379    14087    13302
31    21486    21473    22299    21741    21020
32    14909    14566    14835    13835    13179
33    14187    14591    14598    13065    12426
34    14420    14456    15113    14236    12464
35    14447    14799    15220    13717    12692
36     7828     9031    10434    10465    10404

[17 rows x 50 columns]

In [27]:
df_seoul = df_seoul.drop(['전출지별'],axis=1)
df_seoul = df_seoul.rename({'전입지별':'전입지'})

KeyError: "['전출지별'] not found in axis"

In [28]:
sr_one = df_seoul.loc['경기도']

KeyError: '경기도'